# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.3
cache: cocoapods
xcode_sdk: iphonesimulator9.3

before_install:
 - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
 - pod repo update --silent
 - pod install --project-directory=Example

script:
- xctool test -workspace Example/RxRealm.xcworkspace -scheme RxRealm-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
